### ISSUE TITLE
Version 9.0.0 of directus has just been released with breaking changes

### ISSUE THREAD

**Issue by mark-james** [arladmin/n8n-custom-nodes#1]
Hi @arladmin,
Thanks for creating this great n8n node.

Unfortunately with the release of Directus 9.0.0 stable, they've introduced a breaking change. They've renamed collection to be content. This breaks your node.

I assume it's a fairly straightforward fix, but I'm pretty new to n8n so wouldn't know where to make the change.

Thanks
Mark

**Comment by arladmin** [comment]
Hi @mark-james, thanks for taking an interest in the node and bringing forth this new issue.
I also came across this yesterday, and plan to roll out a fix in the coming few days.

**Comment by arladmin** [comment]
It seems that the breaking changes don't have any impact on the API, and thus, the node.
The node is working fine with the latest Directus version as well.

**Comment by mark-james** [comment]
Thanks @arladmin,
I can only assume I had a mistake in my workflow and incorrectly assumed it was this change. Apologies for the incorrect info, thanks for validating against the latest version.
